/*
  # Seed AI Radar with initial data

  Inserts comprehensive seed data for:
  - News items from major AI sources
  - AI tools directory
  - Business ideas
  - AI prompts
  - Trend keywords
*/

-- Seed News Items
INSERT INTO news_items (title, summary, category, source_name, source_url, trending_score, is_featured, tags, published_at) VALUES
('GPT-5 Officially Announced: 10x Better Reasoning and Real-Time Multimodal', 'OpenAI announces GPT-5 with revolutionary improvements in reasoning, real-time voice, image generation, and coding. The model achieves near-human performance on complex benchmarks.', 'Models', 'OpenAI', 'https://openai.com', 98, true, '{"GPT-5","OpenAI","LLM","Multimodal"}', now() - interval '2 hours'),
('Google Gemini Ultra 2.0 Beats All Benchmarks', 'Google DeepMind releases Gemini Ultra 2.0 with 1M context window, native video understanding, and real-time code execution across 50+ languages.', 'Models', 'Google AI', 'https://deepmind.google', 95, true, '{"Gemini","Google","Benchmark","LLM"}', now() - interval '4 hours'),
('Anthropic Claude 4 Introduces Constitutional AI 2.0', 'Claude 4 launches with enhanced safety features, 500K context window, and groundbreaking computer use capabilities for autonomous agents.', 'Models', 'Anthropic', 'https://anthropic.com', 92, false, '{"Claude","Anthropic","Safety","Agents"}', now() - interval '6 hours'),
('HuggingFace Releases Open-Source GPT-4 Rival: Falcon 180B', 'The AI community celebrates as HuggingFace launches Falcon 180B, matching GPT-4 performance with full open weights available for commercial use.', 'Open Source', 'HuggingFace', 'https://huggingface.co', 88, false, '{"Falcon","OpenSource","HuggingFace","LLM"}', now() - interval '8 hours'),
('AI Coding Tools Now Write 60% of Production Code at Top Startups', 'A new survey reveals that 67% of Silicon Valley startups now use AI-generated code for majority of their codebase, with Cursor and GitHub Copilot leading adoption.', 'Industry', 'GitHub', 'https://github.com', 85, true, '{"Coding","Automation","Cursor","Copilot"}', now() - interval '10 hours'),
('Reddit Bans AI-Generated Content in 50+ Major Subreddits', 'Community revolt against AI spam leads to mass bans, creating new demand for AI detection tools and verified human content platforms.', 'Community', 'Reddit', 'https://reddit.com', 80, false, '{"Reddit","Content","Policy","Detection"}', now() - interval '12 hours'),
('Product Hunt AI Category Hits Record 500 Launches This Week', 'AI products dominate Product Hunt as investors pour $2B into early-stage AI startups. Key trends: AI agents, voice interfaces, and no-code platforms.', 'Startups', 'Product Hunt', 'https://producthunt.com', 77, false, '{"ProductHunt","Startups","Investment","Agents"}', now() - interval '14 hours'),
('YouTube Now Auto-Generates AI Summaries for All Videos', 'YouTube rolls out AI-powered video summaries, chapters, and Q&A features globally, transforming how users consume long-form content.', 'Products', 'YouTube', 'https://youtube.com', 74, false, '{"YouTube","Summaries","Video","Content"}', now() - interval '16 hours'),
('GitHub Trending: 50 AI Repos with 10K+ Stars This Week', 'AI agent frameworks, RAG pipelines, and multimodal models dominate GitHub trending. AutoGen, CrewAI, and LangGraph lead with massive community growth.', 'Open Source', 'GitHub', 'https://github.com', 71, false, '{"GitHub","OpenSource","Agents","RAG"}', now() - interval '18 hours'),
('AI Image Generation Market Reaches $12B: Who Wins?', 'Midjourney, DALL-E 3, Stable Diffusion, and Flux battle for dominance in the AI image market. Analysis of strengths, pricing, and future roadmaps.', 'Market', 'TechCrunch', 'https://techcrunch.com', 68, false, '{"ImageGeneration","Midjourney","DALLE","Market"}', now() - interval '20 hours'),
('New AI Regulation Framework Proposed by EU: What It Means', 'EU introduces comprehensive AI Act enforcement timeline, requiring transparency reports and safety audits for all frontier models by 2025.', 'Policy', 'EU Commission', 'https://ec.europa.eu', 65, false, '{"Regulation","EU","AIAct","Policy"}', now() - interval '22 hours'),
('Mistral AI Raises $600M Series B at $6B Valuation', 'European AI powerhouse Mistral raises massive funding round to compete with OpenAI and Google, with plans for specialized models and enterprise APIs.', 'Startups', 'Mistral AI', 'https://mistral.ai', 82, false, '{"Mistral","Funding","Europe","Startup"}', now() - interval '1 day')
ON CONFLICT DO NOTHING;

-- Seed AI Tools
INSERT INTO ai_tools (name, description, category, website_url, pricing, rating, use_cases, tags, is_featured, is_tool_of_day, upvotes) VALUES
('Cursor', 'AI-first code editor built on VS Code. Write, edit, and debug code with GPT-4 and Claude 3.5 Sonnet. The fastest way to code with AI.', 'Coding', 'https://cursor.sh', 'Free/Pro', 4.9, '{"Code generation","Debugging","Refactoring","Documentation"}', '{"IDE","Coding","VS Code","AI Assistant"}', true, true, 8420),
('Midjourney', 'The world''s most popular AI image generator. Create stunning photorealistic images, artwork, and designs with simple text prompts.', 'Image Generation', 'https://midjourney.com', 'Paid', 4.8, '{"Image creation","Art","Design","Marketing"}', '{"Images","Art","Design","Creative"}', true, false, 12000),
('ElevenLabs', 'Clone any voice with 3 seconds of audio. Create ultra-realistic AI voiceovers in 29 languages. The best text-to-speech platform available.', 'Audio', 'https://elevenlabs.io', 'Free/Pro', 4.8, '{"Voiceover","Podcasts","Audiobooks","Content"}', '{"Voice","TTS","Clone","Audio"}', true, false, 6800),
('Perplexity AI', 'AI-powered search engine that answers questions with cited sources. Real-time internet access with GPT-4 quality responses.', 'Search', 'https://perplexity.ai', 'Free/Pro', 4.7, '{"Research","Search","Q&A","Citations"}', '{"Search","Research","Citations","Real-time"}', true, false, 9200),
('Claude', 'Anthropic''s AI assistant with 200K context window. Best for analysis, writing, coding, and complex reasoning tasks.', 'Assistant', 'https://claude.ai', 'Free/Pro', 4.9, '{"Writing","Analysis","Coding","Research"}', '{"LLM","Assistant","Reasoning","Writing"}', true, false, 11000),
('Sora', 'OpenAI''s text-to-video model. Create realistic videos up to 60 seconds from text descriptions. Revolutionary video generation.', 'Video Generation', 'https://openai.com/sora', 'Waitlist', 4.6, '{"Video creation","Marketing","Content","Film"}', '{"Video","Text-to-Video","OpenAI","Generation"}', false, false, 7600),
('Runway ML', 'Professional AI video editor and generator. Gen-3 model creates cinema-quality videos. Used by major studios and creators.', 'Video Generation', 'https://runwayml.com', 'Free/Pro', 4.5, '{"Video editing","Film","Content creation","VFX"}', '{"Video","Editor","Film","Creative"}', false, false, 5400),
('Notion AI', 'AI writing, summarizing, and organizing built into Notion. Write faster, summarize documents, and manage knowledge effortlessly.', 'Productivity', 'https://notion.so', 'Free/Add-on', 4.4, '{"Writing","Summaries","Notes","Project management"}', '{"Productivity","Notes","Writing","Organization"}', false, false, 8900),
('Copy.ai', 'AI copywriting tool that generates marketing copy, blog posts, social media content, and sales emails in seconds.', 'Content', 'https://copy.ai', 'Free/Pro', 4.3, '{"Marketing copy","Blog posts","Social media","Emails"}', '{"Copywriting","Marketing","Content","Social"}', false, false, 4200),
('Jasper', 'Enterprise AI content platform for teams. Generate branded content at scale with brand voice, tone, and style controls.', 'Content', 'https://jasper.ai', 'Paid', 4.2, '{"Content marketing","Brand content","SEO","Ads"}', '{"Enterprise","Marketing","Brand","Scale"}', false, false, 3800),
('n8n', 'Open-source AI workflow automation. Build complex automations connecting 400+ apps with AI agents, no coding required.', 'Automation', 'https://n8n.io', 'Free/Cloud', 4.7, '{"Automation","Workflows","Integration","AI agents"}', '{"Automation","No-code","Integration","Open-source"}', true, false, 6200),
('Make', 'Visual no-code automation platform. Connect any app, automate any workflow, add AI with drag-and-drop simplicity.', 'Automation', 'https://make.com', 'Free/Pro', 4.5, '{"Automation","Integration","Workflows","Business"}', '{"Automation","No-code","Integration","Visual"}', false, false, 7100),
('Bolt', 'AI-powered full-stack web app builder. Describe your app, and Bolt builds it instantly with React, Next.js, and Supabase.', 'Coding', 'https://bolt.new', 'Free/Pro', 4.8, '{"App building","Web development","Prototyping","No-code"}', '{"Builder","Web","React","No-code"}', true, false, 5900),
('DALL-E 3', 'OpenAI''s image generation model integrated into ChatGPT. Create highly detailed images with precise text rendering capabilities.', 'Image Generation', 'https://openai.com/dall-e-3', 'ChatGPT Plus', 4.6, '{"Image creation","Illustrations","Marketing","Design"}', '{"Images","OpenAI","ChatGPT","Generation"}', false, false, 8100),
('Stable Diffusion', 'Open-source AI image generation model. Run locally or use APIs. Unlimited generation with full customization and LoRA models.', 'Image Generation', 'https://stability.ai', 'Free', 4.4, '{"Image creation","Art","Custom models","Local AI"}', '{"OpenSource","Images","Local","Custom"}', false, false, 9400)
ON CONFLICT DO NOTHING;

-- Seed Business Ideas
INSERT INTO business_ideas (title, problem, solution, target_audience, monetization, difficulty, opportunity_score, how_to_build, category, tags, is_featured) VALUES
('AI Personal Finance Coach', 'People struggle with budgeting, investing, and financial decisions. Financial advisors are expensive ($200-500/hr) and inaccessible.', 'An AI app that analyzes spending patterns, provides personalized investment advice, sets budgets automatically, and answers financial questions 24/7 in conversational language.', 'Millennials and Gen Z earning $40K-$150K who want financial guidance but can''t afford advisors', 'Freemium: $19/mo premium. Affiliate commissions on recommended products. B2B: white-label for banks.', 'Medium', 88, 'Use Bolt.new to build MVP in 48hrs. Connect Plaid API for bank data. Use GPT-4 for advice. Deploy on Supabase. Launch on Product Hunt.', 'FinTech', '{"Finance","AI Advisor","FinTech","Personal"}', true),
('AI Social Media Ghost Writer', 'Business owners and executives know they should post on LinkedIn/Twitter but don''t have time or writing skills. Hiring social media managers costs $3-8K/month.', 'AI that learns your communication style from past content, automatically generates posts in your voice, schedules them, and responds to comments. Full autopilot social presence.', 'CEOs, founders, and B2B professionals who need consistent social presence for lead generation', 'SaaS: $79-299/month per user. Agency white-label at $500+/month. Pay-per-post model.', 'Easy', 92, 'Build with Next.js + OpenAI. Fine-tune on user''s past posts. LinkedIn/Twitter API for scheduling. Deploy on Vercel + Supabase.', 'SaaS', '{"Social Media","Content","LinkedIn","Ghost Writing"}', true),
('AI Real Estate Deal Finder', 'Real estate investors spend 40+ hours per week analyzing hundreds of properties to find undervalued deals. Most miss opportunities due to slow analysis.', 'AI that scans MLS listings in real-time, scores properties by investment potential, calculates ROI projections, and alerts investors to off-market deals before competitors.', 'Real estate investors doing 2-20 deals per year and real estate agents wanting data edge', 'Monthly subscription $99-499 based on markets covered. Lead referral fees. Institutional licensing.', 'Hard', 85, 'Scrape Zillow/Redfin APIs. Build scoring model with ML. SMS/email alerts system. Create dashboard with charts.', 'PropTech', '{"Real Estate","Investment","Analytics","Automation"}', false),
('AI Customer Support Replacement', 'SaaS companies spend $50K-500K per year on customer support. Response times are slow, quality is inconsistent, and support agents burn out.', 'Drop-in AI support agent that integrates with any product via JavaScript snippet. Learns your entire docs, past tickets, and product. Handles 95% of queries automatically.', 'SaaS startups with 100-10,000 customers needing to scale support without headcount', 'Per resolution pricing: $0.50-2.00 per ticket. Monthly subscription $299-2999. Enterprise custom.', 'Medium', 90, 'Build RAG pipeline with your docs. Create ticket ingestion system. Build embeddable chat widget. White-label dashboard for customers.', 'SaaS', '{"Customer Support","SaaS","Automation","Chatbot"}', false),
('AI Recruitment Platform', 'Hiring managers spend 30+ hours screening resumes per role. 75% of applications are unqualified. Best candidates are lost to slow processes.', 'AI that screens all applicants in real-time, scores cultural fit and skills alignment, conducts async video interviews, and presents ranked shortlists with explanations.', 'HR teams at companies hiring 10-500 people per year. RPO agencies. In-house recruiters.', 'Per-hire: $200-500. Monthly platform fee: $499-2999. ATS integrations add-on.', 'Hard', 83, 'Build resume parser. Create video interview system. Score candidates with GPT-4. Integrate with LinkedIn/Indeed. Build HR dashboard.', 'HRTech', '{"Recruitment","HR","Automation","Screening"}', false),
('AI Menu & Recipe Optimizer', 'Restaurants waste 4-10% of revenue on food waste. Menus aren''t optimized for profitability. Chefs struggle to create new dishes that sell.', 'AI that analyzes sales data, suggests menu optimizations for max profit, generates new recipe ideas based on seasonal ingredients, and predicts daily demand to reduce waste.', 'Restaurant owners with 1-50 locations. Food service operators. Catering companies.', 'Monthly SaaS: $99-399. Integration with major POS systems. Inventory management add-on.', 'Medium', 78, 'Integrate with Square/Toast POS. Build demand forecasting model. Create recipe suggestion engine. Mobile-first dashboard.', 'FoodTech', '{"Restaurant","Food","Optimization","Waste"}', false)
ON CONFLICT DO NOTHING;

-- Seed AI Prompts
INSERT INTO ai_prompts (title, prompt_text, platform, category, use_case, tags, is_daily) VALUES
('The Ultimate Business Plan Generator', 'You are a world-class startup advisor with 20 years of experience building and investing in tech companies. I want to start a business in [NICHE]. Please create a comprehensive business plan including: 1) Executive Summary 2) Market Analysis with TAM/SAM/SOM 3) Competitive Analysis 4) Revenue Model with pricing tiers 5) Go-to-Market Strategy 6) 90-day action plan 7) Key metrics to track 8) Potential risks and mitigation. Be specific, data-driven, and actionable. Format as a professional document.', 'ChatGPT', 'Business', 'Business Planning', '{"Business","Startup","Planning","Strategy"}', true),
('Viral Twitter/X Thread Creator', 'You are a viral content strategist who has written threads with 1M+ impressions. Create a viral Twitter/X thread about [TOPIC] that: - Opens with a shocking hook or counterintuitive statement - Contains 8-12 tweets - Each tweet ends with curiosity gap or cliffhanger - Uses short punchy sentences (max 15 words each) - Includes 2-3 data points or statistics - Ends with a clear CTA - Uses power words that trigger engagement. Format: Tweet 1/8, Tweet 2/8, etc. Topic:', 'ChatGPT', 'Content', 'Social Media', '{"Twitter","Viral","Content","Social"}', true),
('10x Your Code Review Speed', 'You are a senior software engineer at Google with expertise in code quality, security, and performance. Review this code and provide: 1) Security vulnerabilities (OWASP Top 10) 2) Performance bottlenecks with specific fixes 3) Code smell and anti-patterns 4) Missing error handling 5) Test coverage gaps 6) Specific refactoring suggestions with code examples. Be brutal and specific. Here''s the code: [PASTE CODE]', 'Claude', 'Coding', 'Code Review', '{"Coding","Review","Security","Performance"}', true),
('Perfect Landing Page Copy', 'You are a CRO specialist and copywriter who has optimized landing pages with 40%+ conversion rates. Write high-converting landing page copy for [PRODUCT/SERVICE] including: 1) Power headline (under 10 words) + subheadline 2) Above-fold hero section 3) 3 core value propositions with proof points 4) Social proof section (testimonial templates) 5) Feature-benefit section (5 features) 6) FAQ section (5 questions) 7) Strong CTA. Target audience: [DESCRIBE AUDIENCE]. Main benefit: [KEY BENEFIT].', 'ChatGPT', 'Marketing', 'Copywriting', '{"Landing Page","Copy","Marketing","CRO"}', false),
('Dream Job Cold Email', 'Act as an elite executive recruiter who places C-suite executives at Fortune 500 companies. Write a cold outreach email for [YOUR NAME] applying to [JOB TITLE] at [COMPANY]. The email should: - Subject line that gets 80%+ open rate - Reference specific company achievement/challenge - Connect candidate''s exact experience to company need - Include one compelling metric or achievement - Social proof (past company or result) - Clear single CTA - Under 150 words total. My background: [PASTE YOUR EXPERIENCE].', 'Claude', 'Career', 'Job Search', '{"Email","Career","Job","Outreach"}', false),
('Create a Stunning Image: Product Photo', 'Professional product photography, [PRODUCT], studio lighting setup, clean white/gradient background, 8K resolution, shallow depth of field, lens flare, photorealistic, commercial advertising style, shot with Canon EOS R5, 100mm macro lens, perfect exposure, color graded --ar 4:5 --v 6 --style raw --q 2', 'Midjourney', 'Design', 'Product Photography', '{"Midjourney","Image","Product","Photography"}', false),
('n8n AI Email Automation Workflow', 'Create an n8n workflow that: 1) Triggers every morning at 8AM 2) Fetches my Gmail inbox from last 24 hours 3) Categorizes each email (urgent/normal/newsletter/spam) using OpenAI 4) Drafts responses for urgent emails using my writing style 5) Summarizes all emails into a daily digest 6) Sends digest to my Telegram. Provide the exact n8n JSON workflow configuration I can import directly.', 'n8n', 'Automation', 'Email Automation', '{"n8n","Automation","Email","Workflow"}', true),
('Gemini: Deep Market Research Report', 'Using your knowledge and web search capabilities, create a comprehensive market research report for the [INDUSTRY] industry in 2024-2025. Include: 1) Market size and CAGR with sources 2) Top 10 players with market share 3) Key trends disrupting the market 4) Consumer behavior shifts 5) Technology adoption curve 6) Investment activity and M&A 7) White space opportunities 8) 3-year forecast. Cite all data sources. Format as an executive briefing.', 'Gemini', 'Research', 'Market Research', '{"Gemini","Research","Market","Analysis"}', false),
('Bolt: Build a Full SaaS App', 'Build a complete SaaS application for [IDEA]. Requirements: - Landing page with pricing tiers - User authentication (email + Google) - Dashboard with key metrics - Core feature: [MAIN FEATURE] - Stripe payment integration - Email notifications - Mobile responsive - Dark mode. Use Next.js 14, Supabase, Tailwind CSS, shadcn/ui. Make it look like a $99/month professional product. Include all pages and components.', 'Bolt', 'Coding', 'App Development', '{"Bolt","SaaS","Development","Full-stack"}', false)
ON CONFLICT DO NOTHING;

-- Seed Trend Keywords
INSERT INTO trend_keywords (keyword, score, change_percent, category, is_viral) VALUES
('AI Agents', 98, 340.5, 'Technology', true),
('Vibe Coding', 95, 890.2, 'Development', true),
('AI Automation', 93, 215.0, 'Automation', true),
('OpenAI GPT-5', 91, 156.3, 'Models', true),
('Claude 4', 89, 134.7, 'Models', false),
('RAG Pipeline', 87, 178.2, 'Technology', false),
('AI Video Generation', 85, 267.4, 'Creative', true),
('Multi-Agent Systems', 83, 312.8, 'Technology', true),
('No-Code AI', 81, 145.6, 'Tools', false),
('AI Side Hustle', 79, 423.1, 'Business', true),
('Prompt Engineering', 77, 89.3, 'Skills', false),
('AI Startup', 75, 198.5, 'Business', false),
('Local LLM', 73, 267.0, 'Technology', false),
('AI Image Generation', 71, 112.4, 'Creative', false),
('CrewAI', 69, 445.2, 'Tools', true),
('LangGraph', 67, 389.7, 'Tools', false),
('Cursor IDE', 65, 234.1, 'Tools', false),
('AI Finance', 63, 167.8, 'Business', false),
('Mistral AI', 61, 143.2, 'Models', false),
('AI Wrapper', 59, 78.5, 'Business', false)
ON CONFLICT DO NOTHING;
